
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 05 08:59:17 CET 2023
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 16;
  public static final int LBRACKET = 34;
  public static final int ASSIGNMENT = 7;
  public static final int INTEGER = 18;
  public static final int OUT = 21;
  public static final int MINUS = 3;
  public static final int SEMICOLON = 36;
  public static final int IS = 19;
  public static final int AND = 9;
  public static final int RECORD = 24;
  public static final int TYPE = 28;
  public static final int COMMA = 35;
  public static final int BEGIN = 10;
  public static final int PUT_LINE = 23;
  public static final int LOOP = 20;
  public static final int PLUS = 2;
  public static final int IF = 17;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int RETURN = 25;
  public static final int RBRACKET = 33;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int NUMBER = 30;
  public static final int NEQ = 6;
  public static final int CONSTANT = 12;
  public static final int COLON = 37;
  public static final int ELSE = 13;
  public static final int WHILE = 29;
  public static final int THEN = 26;
  public static final int END = 14;
  public static final int STRING = 32;
  public static final int FALSE = 15;
  public static final int GT = 5;
  public static final int MULTIPLICATION = 4;
  public static final int PROCEDURE = 22;
  public static final int IDENTIFIER = 31;
}

